In [1]:
import numpy as np
import pandas as pd

In [2]:
import torch

torch.tensor(data,dtype = None,device =None,requires_grad = False)

In [3]:
torch.tensor([1,2,3],device = torch.device('cuda:0'),requires_grad = False)

AssertionError: Torch not compiled with CUDA enabled

In [4]:
torch.tensor([1,2,3],device = torch.device('cpu'),requires_grad = False)

tensor([1, 2, 3])

In [5]:
torch.tensor([4,5,6])

tensor([4, 5, 6])

In [6]:
t = torch.tensor([7,8,9])
t

tensor([7, 8, 9])

In [7]:
type(t)

torch.Tensor

In [9]:
print(t,t.dtype)

tensor([7, 8, 9]) torch.int64


In [11]:
t.type()

'torch.LongTensor'

In [12]:
# Tensor(1) 大写的想当与empty
t1 = torch.Tensor(1)
t2 = torch.tensor(1)
print(t1,t1.dtype)
print(t2,t2.dtype)

tensor([9.1837e-39]) torch.float32
tensor(1) torch.int64


In [13]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
torch.zeros((3,3))

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [16]:
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
torch.linspace(1,10,9).reshape(3,3)

tensor([[ 1.0000,  2.1250,  3.2500],
        [ 4.3750,  5.5000,  6.6250],
        [ 7.7500,  8.8750, 10.0000]])

In [26]:
np.random.random(3)

array([0.08233793, 0.31429847, 0.13359216])

In [33]:
torch.randn(2,3)

tensor([[-0.2664,  1.0111, -0.9607],
        [ 0.6271, -1.0561, -2.6694]])

In [29]:
np.random.randn(3)

array([0.16972804, 1.08559827, 0.33814084])

In [34]:
torch.rand(3,3)

tensor([[0.4682, 0.3446, 0.3197],
        [0.3728, 0.1476, 0.5426],
        [0.8152, 0.0277, 0.8290]])

In [41]:
torch.randint(1,10,(3,3))

tensor([[5, 8, 4],
        [1, 5, 2],
        [6, 6, 8]])

In [44]:
a = np.arange(0,40,10).reshape(4,1)
b = np.arange(0,3)

In [45]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [46]:
b

array([0, 1, 2])

In [47]:
at = torch.from_numpy(a)
bt = torch.from_numpy(b)

In [48]:
at

tensor([[ 0],
        [10],
        [20],
        [30]], dtype=torch.int32)

In [49]:
bt

tensor([0, 1, 2], dtype=torch.int32)

In [58]:
# 随机种子
torch.manual_seed(42)
t = torch.randn(2,3)
t

tensor([[ 0.3367,  0.1288,  0.2345],
        [ 0.2303, -1.1229, -0.1863]])

In [59]:
t.shape

torch.Size([2, 3])

In [60]:
t.size()

torch.Size([2, 3])

In [61]:
t.dim()

2

In [62]:
# 改变形状 ---方法 1
tt = t.view(3,2)
tt

tensor([[ 0.3367,  0.1288],
        [ 0.2345,  0.2303],
        [-1.1229, -0.1863]])

In [63]:
# 改变形状--方法 2
t2 = torch.reshape(t,(3,2))
t2

tensor([[ 0.3367,  0.1288],
        [ 0.2345,  0.2303],
        [-1.1229, -0.1863]])

In [66]:
# 改变形状---方法 3
t.reshape(3,2)

tensor([[ 0.3367,  0.1288],
        [ 0.2345,  0.2303],
        [-1.1229, -0.1863]])

# 索引切片

In [64]:
x = torch.randn(2,3)
x

tensor([[ 2.2082, -0.6380,  0.4617],
        [ 0.2674,  0.5349,  0.8094]])

In [67]:
x[0,:]

tensor([ 2.2082, -0.6380,  0.4617])

In [68]:
x[:,0]

tensor([2.2082, 0.2674])

In [69]:
torch.masked_select(x,x>0)

tensor([2.2082, 0.4617, 0.2674, 0.5349, 0.8094])

# 逐元素操作

In [87]:
t1 = torch.Tensor([1,2,3])
t1

tensor([1., 2., 3.])

In [88]:
t2 = torch.tensor([1.,2.,3.])
t2

tensor([1., 2., 3.])

In [89]:
t1.dtype

torch.float32

In [90]:
t1 + 1

tensor([2., 3., 4.])

In [92]:
print("e^t次方: ",torch.exp(t1))
print("对数:    ",torch.log(t1))
print("平方:    ",torch.pow(t1,2))
print("开方:    ",torch.sqrt(t1))

e^t次方:  tensor([ 2.7183,  7.3891, 20.0855])
对数:     tensor([0.0000, 0.6931, 1.0986])
平方:     tensor([1., 4., 9.])
开方:     tensor([1.0000, 1.4142, 1.7321])


In [94]:
t2 = torch.tensor([-1.,2.,3.])
t2

tensor([-1.,  2.,  3.])

In [95]:
print(torch.sigmoid(t2))
print(f"双曲正切: {torch.tanh(t2)}")
print(torch.relu(t2))

tensor([0.2689, 0.8808, 0.9526])
双曲正切: tensor([-0.7616,  0.9640,  0.9951])
tensor([0., 2., 3.])


# 加法

In [96]:
x = torch.tensor([1,2])
y = torch.tensor([3,4])
z1 = torch.add(x,y)
z2 = x.add(y)
print(f"x: {x}")
print(f"y: {y}")
print(f"z1: {z1}")
print(f"z2: {z2}")

x: tensor([1, 2])
y: tensor([3, 4])
z1: tensor([4, 6])
z2: tensor([4, 6])


# 乘法

In [97]:
torch.mul(x,y)

tensor([3, 8])

In [104]:
print(torch.dot(x,y))

tensor(11)


# 归并操作

In [105]:
t = torch.randn(2,3)
t

tensor([[ 1.1103, -1.6898, -0.9890],
        [ 0.9580,  1.3221,  0.8172]])

In [106]:
# 均值
torch.mean(t,dim = 1)

tensor([-0.5228,  1.0324])

In [107]:
# 标准差
torch.std(t,dim = 1)

tensor([1.4571, 0.2606])

In [109]:
# 累加
torch.cumsum(t,dim = 0)

tensor([[ 1.1103, -1.6898, -0.9890],
        [ 2.0683, -0.3677, -0.1718]])

In [110]:
# 累乘 product 联想多级索引
torch.cumprod(t,dim = 1)

tensor([[ 1.1103, -1.8762,  1.8555],
        [ 0.9580,  1.2666,  1.0350]])

In [111]:
# 范数
torch.norm(t,p = 2,dim = 1)

tensor([2.2508, 1.8258])

# 比较操作

In [112]:
t = torch.tensor([[1,2,3],[4,5,6]])
t

tensor([[1, 2, 3],
        [4, 5, 6]])

In [113]:
torch.max(t,dim = 1)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))

In [114]:
# 前几个
torch.topk(t,k = 1,dim = 1)

torch.return_types.topk(
values=tensor([[3],
        [6]]),
indices=tensor([[2],
        [2]]))

# 矩阵操作

In [115]:
# 一维矩阵的点积 .dot
a = torch.tensor([2,3])
b = torch.tensor([3,4])
torch.dot(a,b)

tensor(18)

In [121]:
# 二维矩阵的点积
x = torch.randint(10,(2,3))
y = torch.randint(6,(3,4))
print("x:")
print(x)
print("y:")
print(y)
print("x*y: ")
torch.mm(x,y)

x:
tensor([[0, 9, 0],
        [9, 1, 8]])
y:
tensor([[5, 4, 5, 2],
        [4, 3, 3, 2],
        [3, 5, 1, 2]])
x*y: 


tensor([[36, 27, 27, 18],
        [73, 79, 56, 36]])

In [136]:
# 复制
print("x: ")
print(x)
x_clone = x.clone()
print("复制函数 <clone()>  x: ")
print(x_clone)

x: 
tensor([[0, 9, 0],
        [9, 1, 8]])
复制函数 <clone()>  x: 
tensor([[0, 9, 0],
        [9, 1, 8]])
