In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from dateutil import parser

In [4]:
from datetime import datetime

In [8]:
df = pd.DataFrame({'a':[1,2,3,np.nan],
                   'b':[4,5,6,7],
                   'c':[np.nan,np.nan,np.nan,np.nan]})

In [9]:
df

a  b   c
0  1.0  4 NaN
1  2.0  5 NaN
2  3.0  6 NaN
3  NaN  7 NaN

In [10]:
df.isnull()

a      b     c
0  False  False  True
1  False  False  True
2  False  False  True
3   True  False  True

In [11]:
df.isnull().sum()

a    1
b    0
c    4
dtype: int64

In [12]:
df.isnull().any()

a     True
b    False
c     True
dtype: bool

In [13]:
df.columns

Index(['a', 'b', 'c'], dtype='object')

In [14]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [15]:
df.values

array([[ 1.,  4., nan],
       [ 2.,  5., nan],
       [ 3.,  6., nan],
       [nan,  7., nan]])

In [16]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [17]:
np.array([[1,2,3]])

array([[1, 2, 3]])

In [18]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.empty(3)

array([1., 1., 1.])

In [22]:
np.empty((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.random.rand(3,3)

array([[0.80539186, 0.53735955, 0.40334537],
       [0.04139594, 0.73163894, 0.88845702],
       [0.75348436, 0.88722284, 0.92764536]])

In [26]:
np.random.randint(1,10,15).reshape(3,5)

array([[6, 7, 1, 5, 5],
       [3, 1, 2, 1, 2],
       [8, 5, 7, 4, 1]])

In [33]:
a = np.eye(3)

In [28]:
np.random.random(3)

array([0.71359798, 0.47689599, 0.79077823])

arr.dtype # 查看数组里每一个元素的数据类型

df.dtypes # 查看DataFrame每一列的数据类型

type() # 查看对象的数据类型

In [34]:
a[True]

array([[[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]])

In [35]:
ser = pd.Series([[1,2,3],[4,5,6]])
ser

0    [1, 2, 3]
1    [4, 5, 6]
dtype: object

In [40]:
ser[0]

[1, 2, 3]

In [41]:
ser[0][0]

1

In [44]:
for i in ser:
    print(i,ser.index)

[1, 2, 3] RangeIndex(start=0, stop=2, step=1)
[4, 5, 6] RangeIndex(start=0, stop=2, step=1)


In [46]:
for i in ser.items():
    print(i)

(0, [1, 2, 3])
(1, [4, 5, 6])


In [47]:
for i in ser.index:
    print(i,ser[i])

0 [1, 2, 3]
1 [4, 5, 6]


In [51]:
for i in enumerate(ser):
    print(i)

(0, [1, 2, 3])
(1, [4, 5, 6])


In [53]:
df = pd.DataFrame({'year':{2000:1.1,2002:1.2},
                   'month':{2000:2.1}})

In [54]:
df

year  month
2000   1.1    2.1
2002   1.2    NaN

In [56]:
df.info()
# 1.对象类型
# 2.行数量
# 3.列数
# 4.每列的非空数据
# 5.每列的数据类型
# 6,各种类型的个数
# 7. 占用的空间大小

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2 entries, 2000 to 2002
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   year    2 non-null      float64
 1   month   1 non-null      float64
dtypes: float64(2)
memory usage: 48.0 bytes


In [60]:
df.describe() # include='object'

year  month
count  2.000000    1.0
mean   1.150000    2.1
std    0.070711    NaN
min    1.100000    2.1
25%    1.125000    2.1
50%    1.150000    2.1
75%    1.175000    2.1
max    1.200000    2.1

In [62]:
df.fillna(method = 'ffill')
# forward backward

year  month
2000   1.1    2.1
2002   1.2    2.1

In [64]:
df.reset_index() # 是否把现索引当成列

index  year  month
0   2000   1.1    2.1
1   2002   1.2    NaN

In [66]:
# df.rename()