In [139]:
# 隐藏警告信息
import warnings
warnings.filterwarnings(action = "ignore")

# 一级标题
## 二级标题
### 三级标题
#### 四级标题
##### 五级标题
###### 六级标题

- 一级标题
    - 二级标题
        - 三级标题

**加粗**

*斜体*

***加粗斜体***

$公式 = 9$

In [1]:
list1 = list(range(1,10))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
list2 = [1,2,3]
list2

[1, 2, 3]

In [3]:
list3 = []
a = [1,2,3,4]
list3 = a
list3

[1, 2, 3, 4]

In [4]:
tuple1 = 1,2
tuple1

(1, 2)

In [5]:
tuple2 = (1,2,3)
tuple2

(1, 2, 3)

In [6]:
tuple3 = 1,
tuple3

(1,)

In [7]:
dict1 = {'a':1}
dict1

{'a': 1}

In [8]:
dict2 = {}
dict2['a'] = 2
dict2

{'a': 2}

In [9]:
l1 = ("abcd")
l2 = [1,2,3,4]
dict1 = dict(zip(l1,l2))
dict1

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [10]:
for k in dict1:
    print(k,dict1[k])

a 1
b 2
c 3
d 4


In [11]:
for k,v in dict1.items():
    print(k,v)

a 1
b 2
c 3
d 4


In [12]:
for i,v in enumerate(list1):
    print(i,v)

0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9


In [13]:
for i in enumerate(list1):
    print(i)

(0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 5)
(5, 6)
(6, 7)
(7, 8)
(8, 9)


In [14]:
for k,v in enumerate(dict1):
    print(k,v)

0 a
1 b
2 c
3 d


In [15]:
# 集合
s = {1,2,3}
s

{1, 2, 3}

In [16]:
s1 = set([1,2,3])
s1

{1, 2, 3}

In [17]:
import numpy as np

In [18]:
arr1 = np.arange(1000000)

In [19]:
list1 = list(range(1000000))

In [20]:
%%timeit -n 50
arr2 = arr1 * 2
# %% 魔法函数

3.71 ms ± 491 µs per loop (mean ± std. dev. of 7 runs, 50 loops each)


In [21]:
%%timeit -n 50
list2 = [x * 2 for x in list1]

229 ms ± 106 ms per loop (mean ± std. dev. of 7 runs, 50 loops each)


In [22]:
123/2.99

41.137123745819395

# 创建ndarray

## 第一种

In [23]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 第二种

In [24]:
data_list = [1,2,3,4]
arr_list = np.array(data_list)
arr_list

array([1, 2, 3, 4])

## 第三种

In [25]:
list33 = list("abdc")
arr3 = np.array(list33)
arr3

array(['a', 'b', 'd', 'c'], dtype='<U1')

In [26]:
data_listnd = [[1,2],[3,4],[5,6]]
arr4 = np.array(data_listnd)
print("多维数组大小:",arr4.shape)
arr4

多维数组大小: (3, 2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
list_5_2 = [[1,1],[2,2],[3,3],[4,4],[5,5]]
arr5_2 = np.array(list_5_2)
print(arr5_2.shape)
arr5_2

(5, 2)


array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [28]:
arr5_2[2]
# 取行

array([3, 3])

In [29]:
arr5_2[3] = 10
arr5_2

array([[ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [10, 10],
       [ 5,  5]])

In [30]:
arr5_2[:,1]
# 取列

array([ 1,  2,  3, 10,  5])

In [31]:
tuple1 = (1,2,3,4)
arr_tuple = np.array(tuple1)
arr_tuple

array([1, 2, 3, 4])

In [32]:
arr_tuple * 3

array([ 3,  6,  9, 12])

In [33]:
dict1 = [{'a':1,'b':2,'c':3},{'aa':11,'bb':22,'cc':33}]
arr_dict = np.array(dict1)
arr_dict

array([{'a': 1, 'b': 2, 'c': 3}, {'aa': 11, 'bb': 22, 'cc': 33}],
      dtype=object)

In [34]:
set1 = {1,2,3}
arr_set = np.array(set1)
arr_set

array({1, 2, 3}, dtype=object)

In [35]:
dict2 = {'a':2,'b':3}
arr_dict2 = np.array(dict2)
arr_dict2

array({'a': 2, 'b': 3}, dtype=object)

In [36]:
set2 = [{1,2,3},{4,5,6}]
arr_set2 = np.array(set2)
arr_set2

array([{1, 2, 3}, {4, 5, 6}], dtype=object)

In [37]:
# arr_dict2 * 3
# 字典不可以

In [38]:
arr_zeros = np.zeros((3,2))
arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
arr_zeros_like = np.zeros_like(arr_zeros)
arr_zeros_like
# like 像arr_zeros

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [40]:
arr_ones = np.ones((2,3))
arr_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
arr_ones_like = np.ones_like(arr_ones)
arr_ones_like
# like 像arr_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
# arr_three = np.threes((3,3)) 
# arr_three
# 不存在

In [43]:
arr_empty = np.empty(20)
arr_empty

array([8.23898318e-312, 6.27463370e-322, 0.00000000e+000, 0.00000000e+000,
       6.79038653e-313, 5.30276956e+180, 1.57076922e-076, 6.98341640e-076,
       4.46470451e-086, 3.35659441e-143, 6.01433264e+175, 6.93885958e+218,
       5.56218858e+180, 3.94356143e+180, 9.51924783e+169, 4.42967836e+175,
       2.80055234e-032, 2.46407051e+184, 6.78880364e-144, 1.50008929e+248])

In [44]:
arr_range = np.array(range(10))
arr_range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr_arange = np.arange(1,10,1.1)
arr_arange

array([1. , 2.1, 3.2, 4.3, 5.4, 6.5, 7.6, 8.7, 9.8])

In [46]:
# arr_range1 = np.array(range(1,10,1.1))
# arr_range1
# 不可以

In [47]:
arr_random_randn = np.random.randn(100)
arr_random_randn
# 符合均值为0,标准差为1的标准正态分布

array([ 0.73020742,  0.192759  , -1.51404541,  1.86906324, -0.30886567,
        0.15305738, -0.64178593, -1.96858588, -0.0205521 , -0.14919022,
       -0.15384062,  1.11422733,  1.84896534,  1.92159021,  0.02300351,
       -0.15158974, -2.87215516, -0.63247313, -1.21344359, -0.05730871,
       -0.97334351, -0.34035315,  0.51353749, -0.12330247, -0.14377229,
        0.27670291,  0.05334325, -0.85427371, -1.70260315, -0.5134943 ,
        1.6480905 , -0.3875434 , -1.41094087,  0.14321002, -0.83596963,
       -1.9787618 ,  0.07024909,  0.36766666,  0.19311496, -0.81107091,
        2.73637435, -0.18191726,  0.17739931,  1.26897424,  0.19830152,
        0.25746125,  1.70834196,  1.23706837, -0.14049694,  0.65883818,
       -0.46602563, -0.10501531,  0.20028552, -0.23949658, -0.91387708,
        1.20860156, -0.50696007,  0.63778895,  0.1885799 , -0.46793624,
        0.36392121, -0.37651938,  0.33556503, -0.22327762, -1.26483787,
        1.13529618,  0.81469423, -0.24678737,  0.2099663 ,  1.44

In [48]:
arr_random_randn.mean()

0.07985282960347075

In [49]:
arr_random_randn.std()

1.0266415607645265

In [50]:
arr_100000 = np.random.randn(10000000)
arr_100000

array([ 0.30015136, -1.67405918,  0.41794703, ..., -0.97038411,
       -1.83512778, -0.55965205])

In [51]:
arr_100000.mean()

-0.0001626569654230313

In [52]:
arr_100000.std()

1.0002506729157885

In [53]:
arr_random_randint = np.random.randint(1,100,10)

In [54]:
arr_random_randint1 = np.random.randint(1,100,10).reshape(5,2)
arr_random_randint1

array([[96, 13],
       [49, 59],
       [38, 67],
       [71, 50],
       [50, 63]])

In [55]:
arr_random_rand = np.random.rand(10)
arr_random_rand

array([0.36203558, 0.11273684, 0.65897878, 0.38266112, 0.52068081,
       0.65293376, 0.79847232, 0.31042757, 0.29187118, 0.08262045])

In [56]:
np.random.seed(0)
arr_random_rand1 = np.random.rand(10)
arr_random_rand1

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152])

In [57]:
np.random.random(10)

array([0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215])

In [58]:
np.random.rand(3,2)
# 后面可以加形状

array([[0.97861834, 0.79915856],
       [0.46147936, 0.78052918],
       [0.11827443, 0.63992102]])

In [59]:
arr_linspace = np.linspace(11,21,100,endpoint = False)
arr_linspace
# linspace 把11到21分成100份
# endpoint (默认值)True尾部包含,False尾部不包含

array([11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3,
       15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4,
       16.5, 16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5,
       17.6, 17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6,
       18.7, 18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7,
       19.8, 19.9, 20. , 20.1, 20.2, 20.3, 20.4, 20.5, 20.6, 20.7, 20.8,
       20.9])

In [60]:
arr_eye = np.eye(5)
arr_eye
# 单位矩阵对角线为1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
arr_identity = np.identity(5)
arr_identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
arr_diag = np.diag([1] * 5)
arr_diag

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [63]:
arr_diag_5 = np.diag([5] * 5)
arr_diag_5

array([[5, 0, 0, 0, 0],
       [0, 5, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 5]])

# random的三种方法

## 第一种

In [64]:
np_random_randn = np.random.randn(10)
np_random_randn
# 符合标准正太分布,均值为0,标准差为1

array([-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502,  2.26975462,
       -1.45436567,  0.04575852, -0.18718385,  1.53277921,  1.46935877])

## 第二种

In [65]:
np_random_randint = np.random.randint(1,100,10)
np_random_randint
# 整数

array([80,  5, 43, 59, 32,  2, 66, 42, 58, 36])

## 第三种

In [66]:
np_random_random = np.random.random(10)
np_random_random
# 0---1 之间的小数

array([0.65314004, 0.17090959, 0.35815217, 0.75068614, 0.60783067,
       0.32504723, 0.03842543, 0.63427406, 0.95894927, 0.65279032])

In [67]:
data1 = [[6,7.5],[1,2]]
arr1 = np.array(data1)

In [68]:
# 几维
print(arr1.ndim)

2


In [69]:
# 形状
print(arr1.shape)

(2, 2)


In [70]:
# 大小---元素个数
print(arr1.size)

4


In [71]:
# 数据类型
print(arr1.dtype)

float64


In [72]:
# 数据所占字节大小
print(arr1.itemsize)

8


In [73]:
print("数组的维数(ndim): ",arr1.ndim) # 数组的维数
print("数组的形状(shape): ",arr1.shape) # 数组的形状
print("数组的大小---元素的个数(size): ",arr1.size) # 数组的大小---元素的个数
print("数组元素的类型(dtype): ",arr1.dtype) # 数组元素的类型
print("数组元素的所占字节的大小(itemsize): ",arr1.itemsize) # 数组元素的所占字节的大小

数组的维数(ndim):  2
数组的形状(shape):  (2, 2)
数组的大小---元素的个数(size):  4
数组元素的类型(dtype):  float64
数组元素的所占字节的大小(itemsize):  8


In [74]:
l = [1,2,3]
type(l) # 查看对象类型:type

list

In [75]:
t = (1,2,3)
type(t)

tuple

In [76]:
s = "abc"
type(s)

str

In [77]:
type(arr1)

numpy.ndarray

In [78]:
arr1.dtype

dtype('float64')

# 创建数组时指定元素类型

In [79]:
arr2 = np.array([1,2,3], dtype = np.float32)
arr22 = np.array([1,2,3], dtype = np.int64)
arr222 = np.array([1,2,3], dtype = np.int)
print("arr2的元素类型: ",arr2.dtype)
print("arr22的元素类型: ",arr22.dtype)
print("arr222的元素类型: ",arr222.dtype)

arr2的元素类型:  float32
arr22的元素类型:  int64
arr222的元素类型:  int32


In [80]:
arr3 = np.array([1,2.0,3.1], dtype = np.float64)
print(arr3.dtype)

float64


In [81]:
# 转换数据类型---astype
arr33 = arr3.astype(np.int32)
print(arr33.dtype)
print(arr3.dtype)

int32
float64


In [82]:
print(arr33.itemsize)
print(arr3.itemsize)

4
8


In [83]:
print(arr33.itemsize * arr33.size)
print(arr3.itemsize * arr3.size)

12
24


## 数组的运算

In [84]:
arr_2_3 = np.array([[1,2,3],[4,5,6]])
arr_2_3

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
print(arr_2_3 + arr_2_3)

[[ 2  4  6]
 [ 8 10 12]]


In [86]:
print(arr_2_3 - arr_2_3)

[[0 0 0]
 [0 0 0]]


In [87]:
print(arr_2_3 * arr_2_3) # 数乘

[[ 1  4  9]
 [16 25 36]]


In [88]:
print(arr_2_3 / arr_2_3)

[[1. 1. 1.]
 [1. 1. 1.]]


In [89]:
arr_2_3.dot(arr_2_3.T) # 点乘

array([[14, 32],
       [32, 77]])

## 切片

In [90]:
arr = np.arange(10)
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [91]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
print(arr[5:8])

[5 6 7]


In [93]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
print(arr2d[1:2,0:1])
arr2d[1:2,0:1]

[[4]]


array([[4]])

In [95]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [96]:
arr2d[2,:]

array([7, 8, 9])

In [97]:
arr2d[:,0:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [98]:
arr2d[1,:2]

array([4, 5])

In [99]:
arr2d = np.array([[0,0,0],[0,0,0],[0,0,0]])
arr3 = arr2d
arr3[0:2,1:3] = 50
arr3

array([[ 0, 50, 50],
       [ 0, 50, 50],
       [ 0,  0,  0]])

In [100]:
arr2d = np.array([[0,0,0],[0,0,0],[0,0,0]])
arr4 = arr2d
arr4[2:,:] = 50
arr4

array([[ 0,  0,  0],
       [ 0,  0,  0],
       [50, 50, 50]])

In [101]:
arr2d = np.array([[0,0,0],[0,0,0],[0,0,0]])
arr5 = arr2d
arr5[:,0:2] = 50
arr5

array([[50, 50,  0],
       [50, 50,  0],
       [50, 50,  0]])

In [102]:
arr2d = np.array([[0,0,0],[0,0,0],[0,0,0]])
arr6 = arr2d
arr6[1:2,0:2] = 50
arr6

array([[ 0,  0,  0],
       [50, 50,  0],
       [ 0,  0,  0]])

In [103]:
names = np.array(['Bob','Joe','Will','Bob',"Will","Joe","Joe"])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [104]:
col = np.array(range(4))

In [105]:
data = np.random.rand(7,4)

In [106]:
print(data)

[[0.63505887 0.99529957 0.58185033 0.41436859]
 [0.4746975  0.6235101  0.33800761 0.67475232]
 [0.31720174 0.77834548 0.94957105 0.66252687]
 [0.01357164 0.6228461  0.67365963 0.971945  ]
 [0.87819347 0.50962438 0.05571469 0.45115921]
 [0.01998767 0.44171092 0.97958673 0.35944446]
 [0.48089353 0.68866118 0.88047589 0.91823547]]


In [107]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [108]:
data[names == "Bob"]

array([[0.63505887, 0.99529957, 0.58185033, 0.41436859],
       [0.01357164, 0.6228461 , 0.67365963, 0.971945  ]])

In [109]:
data[names == "Bob", col == 2]

array([0.58185033, 0.67365963])

In [110]:
data[names != "Bob"]

array([[0.4746975 , 0.6235101 , 0.33800761, 0.67475232],
       [0.31720174, 0.77834548, 0.94957105, 0.66252687],
       [0.87819347, 0.50962438, 0.05571469, 0.45115921],
       [0.01998767, 0.44171092, 0.97958673, 0.35944446],
       [0.48089353, 0.68866118, 0.88047589, 0.91823547]])

In [111]:
data[(names == "Will") | (names == "Joe")]

array([[0.4746975 , 0.6235101 , 0.33800761, 0.67475232],
       [0.31720174, 0.77834548, 0.94957105, 0.66252687],
       [0.87819347, 0.50962438, 0.05571469, 0.45115921],
       [0.01998767, 0.44171092, 0.97958673, 0.35944446],
       [0.48089353, 0.68866118, 0.88047589, 0.91823547]])

In [112]:
data[(names == "Will") & (names == "Joe")]

array([], shape=(0, 4), dtype=float64)

In [113]:
arr2d.transpose() # 转置---T

array([[ 0, 50,  0],
       [ 0, 50,  0],
       [ 0,  0,  0]])

In [114]:
arr2d.T

array([[ 0, 50,  0],
       [ 0, 50,  0],
       [ 0,  0,  0]])

In [115]:
arr = np.array([1,np.e,np.e ** 2,0])

In [116]:
print(arr)

[1.         2.71828183 7.3890561  0.        ]


In [117]:
print(np.max(arr)) #最大值

7.3890560989306495


In [118]:
print(np.min(arr)) # 最小值

0.0


In [119]:
print(np.exp(arr)) # 指数函数

[2.71828183e+00 1.51542622e+01 1.61817799e+03 1.00000000e+00]


In [138]:
import warnings
warnings.filterwarnings(action = "ignore")
print(np.log(arr)) # 对数函数

[  0.   1.   2. -inf]


In [121]:
print(np.sqrt(arr)) # 开方

[1.         1.64872127 2.71828183 0.        ]


In [122]:
print(np.argmax(arr)) # 最大值索引位置

2


In [124]:
print(np.argmin(arr)) # 最小值索引位置

3


In [125]:
print(np.mean(arr)) # 均值

2.7768344818474238


In [126]:
print(np.std(arr)) # 标准差

2.8347824949088896


In [127]:
print(np.var(arr)) # 方差

8.03599179344187


In [132]:
print(np.unique()) # 去重

[0.         1.         2.71828183 7.3890561 ]


In [133]:
print(np.abs(arr)) # 绝对值

[1.         2.71828183 7.3890561  0.        ]


In [136]:
print(np.isinf(arr)) # 数组的各值是否为极限值

[False False False False]


In [146]:
a = np.random.randint(1,101,9).reshape(3,3)
a

array([[57, 61, 78],
       [31, 25,  3],
       [ 4, 95, 99]])

In [148]:
b = np.where(a<60,"不及格",
            np.where(a<=70,"可  以",
                    np.where(a<=80,"  中  ",
                            np.where(a<=90,"  良  ","  优  "))))
b

array([['不及格', '可  以', '  中  '],
       ['不及格', '不及格', '不及格'],
       ['不及格', '  优  ', '  优  ']], dtype='<U5')

In [150]:
np.sort(a,axis = 1)

array([[57, 61, 78],
       [ 3, 25, 31],
       [ 4, 95, 99]])

In [151]:
np.sort(a,axis = -1)

array([[57, 61, 78],
       [ 3, 25, 31],
       [ 4, 95, 99]])

In [152]:
np.sort(a,axis = 0)

array([[ 4, 25,  3],
       [31, 61, 78],
       [57, 95, 99]])

In [153]:
c = a
c

array([[57, 61, 78],
       [31, 25,  3],
       [ 4, 95, 99]])

In [154]:
np.hstack((a,c)) # 横向堆叠

array([[57, 61, 78, 57, 61, 78],
       [31, 25,  3, 31, 25,  3],
       [ 4, 95, 99,  4, 95, 99]])

In [155]:
np.vstack((a,c)) # 纵向堆叠

array([[57, 61, 78],
       [31, 25,  3],
       [ 4, 95, 99],
       [57, 61, 78],
       [31, 25,  3],
       [ 4, 95, 99]])

In [158]:
aa = np.random.randint(1,100,15).reshape(5,3)
aa

array([[14, 41, 73],
       [20, 96, 73],
       [27, 67, 53],
       [68, 62, 15],
       [97,  5, 68]])

In [174]:
np.sort(aa)

array([[14, 41, 73],
       [20, 73, 96],
       [27, 53, 67],
       [15, 62, 68],
       [ 5, 68, 97]])

In [173]:
np.sort(np.sort(aa,axis = 0),axis = 1)

array([[ 5, 14, 15],
       [20, 41, 53],
       [27, 62, 68],
       [67, 68, 73],
       [73, 96, 97]])

In [170]:
np.sort(aa,axis = 0)

array([[14,  5, 15],
       [20, 41, 53],
       [27, 62, 68],
       [68, 67, 73],
       [97, 96, 73]])

In [171]:
np.sort(aa,axis = 1)

array([[14, 41, 73],
       [20, 73, 96],
       [27, 53, 67],
       [15, 62, 68],
       [ 5, 68, 97]])

In [165]:
bb = np.random.randint(1,100,10).reshape(5,2)
bb

array([[12, 87],
       [78, 76],
       [57, 17],
       [25, 30],
       [22, 26]])

In [167]:
cc = bb
cc

array([[12, 87],
       [78, 76],
       [57, 17],
       [25, 30],
       [22, 26]])

In [168]:
np.vstack((bb,cc))

array([[12, 87],
       [78, 76],
       [57, 17],
       [25, 30],
       [22, 26],
       [12, 87],
       [78, 76],
       [57, 17],
       [25, 30],
       [22, 26]])

In [169]:
np.hstack((bb,cc))

array([[12, 87, 12, 87],
       [78, 76, 78, 76],
       [57, 17, 57, 17],
       [25, 30, 25, 30],
       [22, 26, 22, 26]])

## 向上转型机制

In [175]:
xiao = np.arange(5,dtype="float32")

In [176]:
da = np.arange(5,dtype="float64")

In [177]:
c = np.vstack((xiao,da))

In [178]:
c

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [179]:
c.dtype # 新数组里面的元素类型变为高精度

dtype('float64')

## 广播

In [183]:
a = np.array([[0,0,0],[10,10,10],[20,20,20],[30,30,30]])
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [185]:
b = np.array([[0,1,2]])
b

array([[0, 1, 2]])

In [186]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [187]:
aa = np.array([[0,10,10,10],[0,20,20,20],[0,30,30,30]])
aa

array([[ 0, 10, 10, 10],
       [ 0, 20, 20, 20],
       [ 0, 30, 30, 30]])

In [188]:
bb = np.array([[0],[1],[2]])
bb

array([[0],
       [1],
       [2]])

In [189]:
aa + bb

array([[ 0, 10, 10, 10],
       [ 1, 21, 21, 21],
       [ 2, 32, 32, 32]])