In [1]:
import numpy as np

In [2]:
arr1 = np.array([[81, 64, 64, 10],
       [32, 91, 83, 12],
       [69, 78, 67, 17]])

# 数组添加元素
sss=np.vstack((原数组,想添加的数组)) #添加行,参数要有()   
np.vstack((arr1,[81, 64, 64, 10])) #[81, 64, 64, 10]处可以以元组的方式展示   
sss=np.hstack((原数组,想添加的数组)) #添加列,参数要有(),数数据要体现出列的关系   
np.hstack((arr1,[[1],[2],[3]])) #[1],[2],[3]] 可以用元组，但内部元素不要元组   
sss=np.append(原数组,想添加的数组,axis=行为0，列为1) #想添加的数组的维度与原数组维度一致    
sss=np.insert(原数组,位置,想添加的list,axis=行为0，列为1) #二维数据  只要长度一致即可    
sss=np.insert(原一维数组,位置,想添加的list)#一维数据   

### 练习一

In [40]:
arr1

array([[81, 64, 64, 10],
       [32, 91, 83, 12],
       [69, 78, 67, 17]])

In [62]:
#vstack，hstack 实现
#1 为arr1 追加一行（内容为第2行的数据）
np.vstack((arr1,arr1[2,:]))
#2 为arr1 追加两列（内容为第1，2列的数据）
np.hstack((arr1,arr1[:,1:3]))
#3 为arr1 追加-列（内容如为第三列的数据）
np.hstack((arr1,arr1[:,[3]]))

#append 实现
#1 对arr1进行以行的形式追加arr1
np.append(arr1,arr1[:,:],axis = 0)
#2 对arr1进行以列的形式追加arr1
np.append(arr1,arr1[:,:],axis = 1)
#3 对arr1进追加一行内容为 1，2，3，4
np.append(arr1,[[1,2,3,4]],axis = 0)
#4 对arr1进追加一列内容为 1，2，3
np.append(arr1,[[1],[2],[3]],axis = 1)

#insert 实现
#1 对arr1在第1行后追加一行内容为 1，2，3，4
np.insert(arr1,1,[1,2,3,4],axis = 0)
# np.insert(arr1,1,[1,2,3,4],axis=0)
#2 对arr1在地列后追加一行内容为 1，2，3
np.insert(arr1,1,[1,2,3],axis = 1)

array([[81,  1, 64, 64, 10],
       [32,  2, 91, 83, 12],
       [69,  3, 78, 67, 17]])

# 函数
               
np.multiply(mat1,mat2) #矩阵计算对应位置乘法 arr1 * arr2       
np.sort(a,axis=1|0) #排序  ,以第一列对行进行排序，或以第一行对列进行排序  
np.argsort(a,axis=1|0) #排序后的索引位置       
a.ravel() #数组展开为一维度      
np.cumsum(a) #累加函数           
np.where(条件,true,false) #等价于excel的if,可嵌套  
np.unique(数组）#对数据去重   

### 练习二

In [3]:
arr1 = np.array([[81, 64, 64, 10],
       [32, 91, 83, 12],
       [69, 78, 67, 17]])

2

1. 计算arr1各行的平均值并绑定到arr1上


2. 计算arr1各列的总和并添加到arr1上

3. 找到每行最大值所在的列号

4. 找到每列最大值所在的行号

5. 求每行中各列的累积百分比（比如81占第0行的百分比，81+64占第0行的百分比，以此类推）

In [5]:
# 列方向累加求和
np.cumsum(arr1,axis=1)

array([[ 81, 145, 209, 219],
       [ 32, 123, 206, 218],
       [ 69, 147, 214, 231]], dtype=int32)

6. 对arr1 进行不及格，及格， 中，良，优的划分 结果为arr2

7. 把arr1 变为一维数据

8. 对arr2进行去重处理

In [5]:
arr1 = np.array([[81, 64, 64, 10],
                 [32, 91, 83, 12],
                 [69, 78, 67, 17]])

### 练习三

In [16]:
arr = [[28, 92, 51, 83, 25],
       [84, 32, 99, 43, 78],
       [55, 42, 30, 48, 43]]
#假定 行分别为小明， 小红， 小白
#假定列分别为数学，语文，英语，物理, 化学
arr = np.array(arr)
renming = np.array(["小明","小红","小白"])
chengji = np.array(["数学","语文","英语","物理","化学"])

In [79]:
#1 找到每人最高分的科目

#2 找到每科最高分的人名

#3 计算每人的不及格科目数

#4 按平均分对学生进行排序


#5 找出成绩最稳定的人

#6 找出成绩最好的科目

#7 计算每科的及格率

#8 按总分对科目进行排序

#9 对成绩进行化整 (如 20，90，50，80，20 等)

#10 统计所用几个数，不及格数， 人数，科目数


array([[20, 90, 50, 80, 20],
       [80, 30, 90, 40, 70],
       [50, 40, 30, 40, 40]])

### 练习四

In [14]:
#1 对arr 随机设计几个-1

#2 对arr 的缺失值进行以列的形式进行均值替换-1


array([[-1, 92, -1, 83, 25],
       [84, 32, 99, 43, 78],
       [-1, 42, -1, 48, -1]])