In [1]:
import numpy as np

用5种方法创建2行3列的数组arr

In [2]:
arr1 = np.array([[1,2,3],[3,4,5]])
arr1

array([[1, 2, 3],
       [3, 4, 5]])

In [3]:
list1 = [[1,2,3],[4,5,6]]
arr2 = np.array(list1)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
arr3 = np.zeros([2,3])
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr4 = np.random.rand(2,3)
arr4

array([[5.83183976e-01, 7.32477768e-01, 6.72572292e-05],
       [7.26625042e-01, 2.96556589e-01, 6.40897423e-01]])

In [6]:
arr5 = np.ones_like(arr4)
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [7]:
arr6 = np.random.randint(1,10,6).reshape(2,3)
arr6

array([[6, 5, 8],
       [7, 4, 9]])

1. 用三种方法求 求arr的最小值,最大值，合计，标准差，方差

In [8]:
arr1 = np.random.randint(1,100,15).reshape(3,5)
arr1

array([[42, 84, 93, 46, 45],
       [31, 12, 23, 89, 49],
       [58, 68,  3, 77, 24]])

In [9]:
arr1.max() # 第一种

93

In [10]:
np.max(arr1) # 第二种

93

In [11]:
# arr1.argmax()//4
arr1.argmax()//arr1.shape[1]

0

In [12]:
# arr1.argmax() % 4
arr1.argmax() % arr1.shape[1]

2

In [13]:
# 第三种
arr1[arr1.argmax()//arr1.shape[1],arr1.argmax()%arr1.shape[1]]

93

In [14]:
arr1.shape[0] # 数组行数

3

In [15]:
arr1.shape[1] # 数组列数

5

2. 对arr 进行对数变换

In [16]:
arr1

array([[42, 84, 93, 46, 45],
       [31, 12, 23, 89, 49],
       [58, 68,  3, 77, 24]])

In [17]:
np.log(arr1)

array([[3.73766962, 4.4308168 , 4.53259949, 3.8286414 , 3.80666249],
       [3.4339872 , 2.48490665, 3.13549422, 4.48863637, 3.8918203 ],
       [4.06044301, 4.21950771, 1.09861229, 4.34380542, 3.17805383]])

3. 找出 arr 最大值，最小值所在的位置,（行列号）

In [18]:
np.where(arr1 == np.max(arr1)) # 第二种

(array([0], dtype=int64), array([2], dtype=int64))

In [19]:
arr1.argmax()//arr1.shape[1] # 第一种

0

In [23]:
arr1.argmax() % arr1.shape[1] # 第一种

2

4. 对arr1各元素向下取整，格式如下 38，27，12 等等

In [24]:
np.ceil(np.log(arr1))

array([[4., 5., 5., 4., 4.],
       [4., 3., 4., 5., 4.],
       [5., 5., 2., 5., 4.]])

5. 对arr1各元素向上取整，格式如下 39，28，13 等等

In [25]:
np.floor(np.log(arr1))

array([[3., 4., 4., 3., 3.],
       [3., 2., 3., 4., 3.],
       [4., 4., 1., 4., 3.]])

6. 对arr1各元素进行4舍5入进行保留2位小数点

In [26]:
np.round(np.log(arr1),decimals=2)

array([[3.74, 4.43, 4.53, 3.83, 3.81],
       [3.43, 2.48, 3.14, 4.49, 3.89],
       [4.06, 4.22, 1.1 , 4.34, 3.18]])

In [27]:
np.log(arr1).round(2)

array([[3.74, 4.43, 4.53, 3.83, 3.81],
       [3.43, 2.48, 3.14, 4.49, 3.89],
       [4.06, 4.22, 1.1 , 4.34, 3.18]])

7. 对arr1各元素进行开方

In [28]:
np.sqrt(arr1)

array([[6.4807407 , 9.16515139, 9.64365076, 6.78232998, 6.70820393],
       [5.56776436, 3.46410162, 4.79583152, 9.43398113, 7.        ],
       [7.61577311, 8.24621125, 1.73205081, 8.77496439, 4.89897949]])

8. 对arr1用两种方式进行转置

In [29]:
arr1

array([[42, 84, 93, 46, 45],
       [31, 12, 23, 89, 49],
       [58, 68,  3, 77, 24]])

In [30]:
arr1.T

array([[42, 31, 58],
       [84, 12, 68],
       [93, 23,  3],
       [46, 89, 77],
       [45, 49, 24]])

In [31]:
arr1.transpose()

array([[42, 31, 58],
       [84, 12, 68],
       [93, 23,  3],
       [46, 89, 77],
       [45, 49, 24]])

9. 取0,2行，1，3列数数据

In [32]:
arr1

array([[42, 84, 93, 46, 45],
       [31, 12, 23, 89, 49],
       [58, 68,  3, 77, 24]])

In [33]:
arr1[0:,[1,3]]

array([[84, 46],
       [12, 89],
       [68, 77]])

10. 取奇数列数据

In [34]:
arr1[:,1::2]

array([[84, 46],
       [12, 89],
       [68, 77]])

11. 取偶数行数据

In [35]:
arr1[0::2,:]

array([[42, 84, 93, 46, 45],
       [58, 68,  3, 77, 24]])

12. 第0列大于5的所有行数据

In [41]:
arr1

array([[42, 84, 93, 46, 45],
       [31, 12, 23, 89, 49],
       [58, 68,  3, 77, 24]])

In [42]:
arr1[arr1[:,0]>60]

array([], shape=(0, 5), dtype=int32)

In [43]:
arr1[arr1[:,0]>60][:,0]

array([], dtype=int32)

13. 第0列大于3并且第1列大于5的数据

In [35]:
arr1[(arr1[:,0]>3) & (arr1[:,1]>3)]

array([[ 8,  5,  8, 76, 26],
       [31, 64, 82, 88, 37],
       [50, 50, 14, 34, 74]])

In [36]:
arr1[(arr1[:,0]>3) & (arr1[:,1]>3)][:,[0,1]]

array([[ 8,  5],
       [31, 64],
       [50, 50]])

14. 第0行大于1的所有列

In [37]:
arr1[0,:]

array([ 8,  5,  8, 76, 26])

In [38]:
arr1[0,arr1[0,:]>20]

array([76, 26])

15. 第2列大于5的数行，第2行大于5的列

In [39]:
arr1[:3,]

array([[ 8,  5,  8, 76, 26],
       [31, 64, 82, 88, 37],
       [50, 50, 14, 34, 74]])

In [40]:
arr1

array([[ 8,  5,  8, 76, 26],
       [31, 64, 82, 88, 37],
       [50, 50, 14, 34, 74]])

In [50]:
arr1[arr1[:,2]>30,2]

array([82])

In [51]:
arr1[2,arr1[2,:]>30]

array([50, 50, 34, 74])

In [49]:
arr1[arr1[:,2]>30,arr1[2,:]>30]

array([31, 64, 88, 37])

In [44]:
arr1

array([[42, 84, 93, 46, 45],
       [31, 12, 23, 89, 49],
       [58, 68,  3, 77, 24]])

In [48]:
arr1[arr1>10] = arr1.mean()
arr1

array([[49, 49, 49, 49, 49],
       [49, 49, 49, 49, 49],
       [49, 49,  3, 49, 49]])

## 多维数组ndarray的创建
np.array(元组|列表) #把元组或列表转化为数组  
np.arange([开始数值,]结束数值[,步长]) #获取开始到结束的步长序列  
np.linspace(开始,结束,组数,endpoint=是否包含结束值) #线性分段  
np.zeros((行数，列数) [,dtype=元素数据类型]) #创建元素为0的array  
np.ones((行数，列数) [,dtype=元素数据类型]) #创建元素为1的array  
np.eye(N) #创建N行N列对角线为1的array  
np.empty((行数，列数),[,dtype=元素数据类型])  #默认值的数组  
np.random.rand(行数，列数) #随机0-1之间的数   
np.random.randint(开始值,结束值,size=(行，列)) #开始~结束的指定个随机数  
np.random.randn(N) #正态分布小的N个随机数  

## 数组属性（属性名后没有小括号）
arr.ndim  #数组的维度

arr.shape #数组的行列数

arr.size  #数组的元素个数  等价于（len()）

arr.dtype #数组元素的类型

##  数组引用
1. 切片    开始:结束:步长 #索引从0开始，左闭右开

- 取一行
    arr[0] 直接给行号，多行时，行号用[] 括起来
    arr[0,:] #行号，所有列。 所有行或所有列时用 ： 表示

- 取一列
    arr[:,0] #所有行，列号
    arr[:,0]
2. 条件取(按True,False 对应位置取)
    arr[行条件,列条件]

## 数组函数
arr.reshape(数值1,数值2,...) #重塑元素类型  
arr.max() # 等价于 np.max(arr)  
arr.min() # 等价于 np.min(arr)  
arr.mean() # 等价于 np.mean(arr)  
arr.sum()  # 等价于 np.sum(arr)    
arr.log() #等价于 np.log(arr)  e为底的对数   
arr.exp() #等价于 np.exp(arr)  e的几次方    
arr.std() #等价于 np.std(arr)  arr的标准差    
arr.var() #等价于 np.var(arr) arr的方差     
arr.argmax() #等价于 np.argmax(arr) 最大值所在的位置      
arr.argmin() #等价于 np.argmin(arr) 最小值所在的位置   
arr.floor() #等价于 np.floor(arr)  小于数组元素的最大整数     
arr.ceil() #等价于 np.ceil(arr)   大于数组元素的最小整数    
arr.round(n） #等价于 np.round(arr）  数组元素保留n位小数    
arr.sqrt()    #等价于 np.sqrt(arr)  
arr.T   或   arr.transpose()  #矩阵转置  
arr.dot(arr.T) #等价于 np.dot(arr,arr.T) #进行矩阵乘法