In [24]:
import numpy as np

1.创建一个包含数字0-9的一维数组, 数据量为20

In [25]:
arr1 = np.random.randint(0,10,20)
arr1

array([8, 4, 3, 1, 6, 0, 8, 7, 9, 1, 6, 6, 0, 2, 9, 7, 1, 5, 8, 6])

2.创建一个包含数字0-8的二维数组, 数据量为10

In [26]:
arr2 = np.random.randint(0,9,10).reshape(2,5)
arr2

array([[4, 3, 2, 1, 1],
       [2, 8, 4, 7, 8]])

3.创建一个包含数字0-20的3\*3随机数组

In [27]:
arr3 = np.random.randint(0,21,9).reshape(3,3)
arr3

array([[ 8,  5,  7],
       [ 9, 19, 19],
       [11,  2, 15]])

5.查看np.zeros((5,4))占用内存的大小  hint：获取每个元素的大小

In [28]:
arr5 = np.zeros((5,4))
arr5
print(arr5.itemsize * arr5.size)
print(arr5.itemsize)

160
8


7.逆序np.arange(10)

In [29]:
arr7 = np.arange(10)
arr7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr7[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

8.获取np.arange(10)里所有的偶数

In [31]:
arr8 = np.arange(10)
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr8[::2]

array([0, 2, 4, 6, 8])

In [33]:
arr8[arr8%2==0]

array([0, 2, 4, 6, 8])

9.把np.arange(10)里所有的偶数替换为0

In [34]:
arr9 = np.arange(10)
arr9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
arr9[::2] = 0
arr9

array([0, 1, 0, 3, 0, 5, 0, 7, 0, 9])

10.把np.arange(10)变成5×2的矩阵

In [36]:
arr10 = np.arange(10).reshape(5,2)
arr10

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

11.把np.arange(10),np.arange(20)变成5列垂直叠加形式

In [37]:
arr11 = np.arange(10).reshape(-1,5)
arr11

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [38]:
arr20 = np.arange(20).reshape(-1,5)
arr20

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [39]:
np.concatenate([arr11,arr20],axis = 0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

12.水平叠加11题中的数组

In [40]:
arr11 = np.arange(10).reshape(5,2)
arr11

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
arr20 = np.arange(20).reshape(5,4)
arr20

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [42]:
np.concatenate([arr11,arr20],axis = 1)

array([[ 0,  1,  0,  1,  2,  3],
       [ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  8,  9, 10, 11],
       [ 6,  7, 12, 13, 14, 15],
       [ 8,  9, 16, 17, 18, 19]])

13.创建一个矩阵，外层为1，剩下全是0

In [43]:
arr13 = np.ones([4,4])
arr13[1:len(arr13) - 1,1:len(arr13) - 1] = 0
arr13

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

14.把np.random.random(10)中最大的数替换成正无穷

In [44]:
arr14 = np.random.random(10)
arr14[np.max(arr14)==arr14] = np.inf
arr14

array([0.30048161, 0.55003013, 0.1952587 , 0.46865056, 0.55947914,
       0.52628424, 0.55630282, 0.0690437 ,        inf, 0.89786209])

16.交换np.arange(9).reshape(3,3)的后两列 hint：花式索引

In [45]:
arr16 = np.arange(9).reshape(3,3)
arr16

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
arr16 = arr16[:,[0,2,1]]
arr16

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [47]:
# a = np.arange(9).reshape(3,3)
# a = a[[1,2,0],:]
# a

17.反转np.arange(9).reshape(3,3)的行

In [48]:
arr17 = np.arange(9).reshape(3,3)
arr17

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr17 = arr17[:,[1,2,0]]
arr17

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

In [50]:
arr17 = arr17[:,[2,1,0]]
arr17

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

In [51]:
arr17 = arr17[:,[1,2,0]]
arr17

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [52]:
arr111 = np.empty((8,4))
for i in range(8):
    arr111[i] = i
arr111

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [61]:
arr111[[3,2,1]]

array([[3., 3., 3., 3.],
       [2., 2., 2., 2.],
       [1., 1., 1., 1.]])

In [58]:
arr111[:,[3,2,1]]

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.],
       [5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.]])

In [60]:
arr111[[4,2,1],[1,2,3]]

array([4., 2., 1.])